packages:
  - "apps/*"
  - "packages/*"
overrides:
  '@types/react': 19.2.17
allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  esbuild: true
  msgpackr-extract: true
  prisma: true
  sharp: true
